# Generated by Django 3.1.5 on 2022-03-24 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='available_courses',
            name='course_instructor',
        ),
        migrations.AlterField(
            model_name='available_courses',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='class_courses_mapping',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
