# Generated by Django 4.0.3 on 2022-03-23 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0002_initial'),
        ('loginapp', '0004_remove_user_signup_database_class_course_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_signup_database',
            name='class_course_field',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='courseapp.class_courses_mapping'),
        ),
        migrations.AddField(
            model_name='user_signup_database',
            name='verfied_user',
            field=models.BooleanField(default=False),
        ),
    ]
